#!/usr/bin/env python3
"""Generate SVG for SP-047 Secure Agentic AI Frameworks.

WARNING: This script overwrites the hand-crafted SVG at OUTPUT path.
All visual elements (including Role Responsibilities bar) MUST be
generated by this script. Do not add hand-edits to the SVG that are
not also reflected here — they WILL be lost on next generation.
"""

OUTPUT = "/Users/tobias.christen/osa-workspace/website/public/images/sp-047-secure-agentic-ai-frameworks.svg"

FONT  = "GillSans, 'Gill Sans MT', Calibri, sans-serif"
NAVY  = "#003459"
TEAL  = "#007EA7"
SKY   = "#00A8E8"
NIGHT = "#00171F"
WHITE = "#FFFFFF"
LIGHT = "#F8FAFC"

CRITICAL_SET = {
    "AC-03","AC-04","AC-05","AC-06","AU-02","AU-03",
    "CA-07","CM-07","IR-04","SA-09","SC-07","SI-10",
}

def pill_path(x, y, w, h, r=8):
    r = min(r, h/2, w/2)
    k = r * 0.552
    x2, y2 = x + w, y + h
    return (
        f"M{x+r},{y} L{x2-r},{y} "
        f"C{x2-r+k:.3f},{y} {x2},{y+r-k:.3f} {x2},{y+r} "
        f"L{x2},{y2-r} "
        f"C{x2},{y2-r+k:.3f} {x2-r+k:.3f},{y2} {x2-r},{y2} "
        f"L{x+r},{y2} "
        f"C{x+r-k:.3f},{y2} {x},{y2-r+k:.3f} {x},{y2-r} "
        f"L{x},{y+r} "
        f"C{x},{y+r-k:.3f} {x+r-k:.3f},{y} {x+r},{y} z"
    )


def badge_svg(x, y, label, critical=False, link=None):
    w  = max(34, int(len(label)*6.0 + 14))
    h  = 16
    p  = pill_path(x, y, w, h, 8)
    cx = x + w/2
    cy = y + h/2
    if critical:
        fc, fo, sc, so, tc = NIGHT, "0.12", NAVY, "0.6", NAVY
    else:
        fc, fo, sc, so, tc = TEAL, "0.12", TEAL, "0.4", "#005F7F"
    inner = (
        f'<path d="{p}" fill="{fc}" fill-opacity="{fo}" '
        f'stroke="{sc}" stroke-opacity="{so}" stroke-width="1"/>'
        f'<text font-family="{FONT}" font-size="8" fill="{tc}" '
        f'text-anchor="middle" dominant-baseline="central" '
        f'x="{cx:.1f}" y="{cy:.1f}">{label}</text>'
    )
    if link:
        return f'<a xlink:href="{link}"><g>{inner}</g></a>'
    return f'<g>{inner}</g>'


def badge_row_svg(x, y, controls, gap=4):
    out = []
    cx = x
    for ctrl in controls:
        crit = ctrl in CRITICAL_SET
        w = max(34, int(len(ctrl)*6.0 + 14))
        slug = ctrl.lower()
        out.append(badge_svg(cx, y, ctrl, critical=crit, link=f"/controls/{slug}"))
        cx += w + gap
    return "\n    ".join(out)


def kca_box(x, y, w, h, color, title, items, controls, hdr_h=22):
    r = 6; k = r*0.552
    parts = []
    parts.append(
        f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{r}" ry="{r}" '
        f'fill="{LIGHT}" stroke="{color}" stroke-opacity="0.35" stroke-width="1.5"/>'
    )
    hx2 = x+w
    hdr_path = (
        f"M{x+r},{y} L{hx2-r},{y} "
        f"C{hx2-r+k:.3f},{y} {hx2},{y+r-k:.3f} {hx2},{y+r} "
        f"L{hx2},{y+hdr_h} L{x},{y+hdr_h} "
        f"L{x},{y+r} C{x},{y+r-k:.3f} {x+r-k:.3f},{y} {x+r},{y} z"
    )
    parts.append(f'<path d="{hdr_path}" fill="{color}"/>')
    tcx = x + w/2; tcy = y + hdr_h/2
    parts.append(
        f'<text font-family="{FONT}" font-size="9.5" font-weight="700" '
        f'letter-spacing="0.8" fill="{WHITE}" text-anchor="middle" '
        f'dominant-baseline="central" x="{tcx:.1f}" y="{tcy:.1f}">{title}</text>'
    )
    BULLET = "\u25AA"
    iy = y + hdr_h + 14
    for item in items:
        parts.append(
            f'<text font-family="{FONT}" font-size="8.2" fill="#334155" '
            f'x="{x+12}" y="{iy:.1f}">'
            f'<tspan fill="{color}" font-size="9">{BULLET}</tspan> {item}</text>'
        )
        iy += 13
    badge_y = y + h - 22
    parts.append(badge_row_svg(x+10, badge_y, [c[0] for c in controls]))
    return "\n    ".join(parts)


def bottom_panel(x, y, w, h, color, title, sub_items, summary_controls, hdr_h=22):
    r = 6; k = r*0.552
    parts = []
    parts.append(
        f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{r}" ry="{r}" '
        f'fill="{LIGHT}" stroke="{color}" stroke-opacity="0.35" stroke-width="1.5"/>'
    )
    hx2 = x+w
    hdr_path = (
        f"M{x+r},{y} L{hx2-r},{y} "
        f"C{hx2-r+k:.3f},{y} {hx2},{y+r-k:.3f} {hx2},{y+r} "
        f"L{hx2},{y+hdr_h} L{x},{y+hdr_h} "
        f"L{x},{y+r} C{x},{y+r-k:.3f} {x+r-k:.3f},{y} {x+r},{y} z"
    )
    parts.append(f'<path d="{hdr_path}" fill="{color}"/>')
    tcx = x + w/2; tcy = y + hdr_h/2
    parts.append(
        f'<text font-family="{FONT}" font-size="9.5" font-weight="700" '
        f'letter-spacing="0.8" fill="{WHITE}" text-anchor="middle" '
        f'dominant-baseline="central" x="{tcx:.1f}" y="{tcy:.1f}">{title}</text>'
    )
    BULLET = "\u25AA"
    col_w = w / 2
    for idx, (item_label, item_ctrls) in enumerate(sub_items):
        col = idx % 2
        row = idx // 2
        ix = x + 12 + col * col_w
        iy = y + hdr_h + 14 + row * 30
        parts.append(
            f'<text font-family="{FONT}" font-size="8.2" fill="#334155" '
            f'x="{ix:.1f}" y="{iy:.1f}">'
            f'<tspan fill="{color}" font-size="9">{BULLET}</tspan> {item_label}</text>'
        )
        bx2 = ix + 10; by2 = iy + 9
        for ctrl in item_ctrls:
            crit = ctrl in CRITICAL_SET
            bw2 = max(34, int(len(ctrl)*6.0 + 14))
            slug = ctrl.lower()
            parts.append(badge_svg(bx2, by2, ctrl, critical=crit, link=f"/controls/{slug}"))
            bx2 += bw2 + 3
    badge_y = y + h - 22
    parts.append(badge_row_svg(x+10, badge_y, [c[0] for c in summary_controls]))
    return "\n    ".join(parts)

def build_svg():
    lines = []
    L = lines.append

    L('<?xml version="1.0" encoding="UTF-8"?>')
    L('<svg xmlns="http://www.w3.org/2000/svg" '
      'xmlns:xlink="http://www.w3.org/1999/xlink" '
      'viewBox="0 0 960 720" width="960" height="720">')
    L(f'  <rect width="960" height="720" fill="{LIGHT}"/>')
    L('  <g>')

    # ── HEADER ────────────────────────────────────────────────────────────────
    L(f'    <rect x="0" y="0" width="960" height="62" fill="{NIGHT}"/>')
    bp = pill_path(18, 21, 52, 20, 10)
    L(f'    <path d="{bp}" fill="{SKY}" fill-opacity="0.25" stroke="{SKY}" '
      f'stroke-opacity="0.7" stroke-width="1"/>')
    L(f'    <text font-family="{FONT}" font-size="10" font-weight="700" fill="{SKY}" '
      f'text-anchor="middle" dominant-baseline="central" x="44" y="31">SP-047</text>')
    L(f'    <text font-family="{FONT}" font-size="21" font-weight="700" fill="{WHITE}" '
      f'x="82" y="28" dominant-baseline="central">SECURE AGENTIC AI FRAMEWORKS</text>')
    L(f'    <text font-family="{FONT}" font-size="9" fill="{WHITE}" fill-opacity="0.68" '
      f'x="82" y="50" dominant-baseline="central">'
      f'OWASP AGENTIC AI \u00b7 NIST AI RMF \u00b7 MAESTRO \u00b7 NIST 800-53 REV5</text>')

    # ── ROLE RESPONSIBILITIES BAR ────────────────────────────────────────────
    L(f'    <text font-family="{FONT}" font-size="9" fill="#94A3B8" '
      f'letter-spacing="1.5" text-anchor="middle" x="480" y="81">'
      f'ROLE RESPONSIBILITIES</text>')
    # Developer
    L(f'    <rect x="10" y="88" width="306" height="28" rx="4" fill="{NAVY}" opacity="0.5"/>')
    L(f'    <text font-family="{FONT}" font-size="9" font-weight="bold" fill="{WHITE}" '
      f'text-anchor="middle" x="163" y="99">DEVELOPER</text>')
    L(f'    <text font-family="{FONT}" font-size="7.5" fill="#B8DFF0" '
      f'text-anchor="middle" x="163" y="111">'
      f'Implements sandboxes, guardrails, kill switches &amp; adversarial tests</text>')
    # Architect
    L(f'    <rect x="324" y="88" width="306" height="28" rx="4" fill="{NAVY}" opacity="0.5"/>')
    L(f'    <text font-family="{FONT}" font-size="9" font-weight="bold" fill="{WHITE}" '
      f'text-anchor="middle" x="477" y="99">ARCHITECT</text>')
    L(f'    <text font-family="{FONT}" font-size="7.5" fill="#B8DFF0" '
      f'text-anchor="middle" x="477" y="111">'
      f'Designs isolation, trust models, guardrails &amp; promotion gates</text>')
    # Business Owner
    L(f'    <rect x="638" y="88" width="312" height="28" rx="4" fill="{NAVY}" opacity="0.5"/>')
    L(f'    <text font-family="{FONT}" font-size="9" font-weight="bold" fill="{WHITE}" '
      f'text-anchor="middle" x="794" y="99">BUSINESS OWNER</text>')
    L(f'    <text font-family="{FONT}" font-size="7.5" fill="#B8DFF0" '
      f'text-anchor="middle" x="794" y="111">'
      f'Defines autonomy tiers, data access, incident criteria</text>')

    # ── TOP ROW ───────────────────────────────────────────────────────────────
    row1_y = 124; row1_h = 210; cw = 306; gap = 12
    xs = [10, 10+cw+gap, 10+2*(cw+gap)]

    L('    <!-- TOP ROW -->')
    L('    ' + kca_box(xs[0], row1_y, cw, row1_h, NAVY,
        'AGENT EXECUTION ISOLATION',
        ['Ephemeral Containers (Read-Only Root FS)',
         'Network Allowlist (Egress Whitelisting)',
         'gVisor / Firecracker Sandboxing',
         'Non-Root, Scoped IAM, Expiring Tokens'],
        [('SC-07',True),('CM-07',True),('SC-39',False),('AC-06',True)]))
    L('    ' + kca_box(xs[1], row1_y, cw, row1_h, TEAL,
        'TOOL REGISTRY &amp; PLUGIN GOVERNANCE',
        ['Centralised MCP Server Registry',
         'Tool Risk Rating &amp; Data Classification',
         'Security Review Before Registration',
         'Source Audit for Community Tools',
         'Quarterly Tool Access Review'],
        [('CM-08',False),('AC-03',True),('CM-03',False),('SA-04',False),('SA-11',False)]))
    L('    ' + kca_box(xs[2], row1_y, cw, row1_h, SKY,
        'GUARDRAILS ARCHITECTURE',
        ['Multi-Layer Input/Output Filtering',
         'Prompt Injection &amp; Jailbreak Detection',
         'Info Flow Enforcement (No PII to External)',
         'Infrastructure-Level Network Enforcement',
         'Adversarial Guardrail Testing (Red Team)'],
        [('SI-10',True),('AC-04',True),('CM-02',False),('SC-07',True)]))

    # ── MIDDLE ROW ────────────────────────────────────────────────────────────
    row2_y = 346; row2_h = 170

    L('    <!-- MIDDLE ROW -->')
    L('    ' + kca_box(xs[0], row2_y, cw, row2_h, NAVY,
        'RAG PIPELINE SECURITY',
        ['Vector Store Encryption at Rest',
         'Document Classification Before Ingestion',
         'Retrieval-Level Authorisation Filtering',
         'RAG Poisoning Detection (Provenance)',
         'Data Source Registry'],
        [('SC-28',False),('AC-04',True),('SI-10',True),('CM-08',False)]))
    L('    ' + kca_box(xs[1], row2_y, cw, row2_h, TEAL,
        'MULTI-AGENT TRUST',
        ['Agent Identity (Persistent, Auditable)',
         'Delegation Chain: No Privilege Escalation',
         'Context Isolation Between Agents',
         'Agent-to-Agent Auth (Short-Lived Tokens)',
         'Inter-Agent Messages = Trust Boundary'],
        [('AC-05',True),('IA-04',False),('AU-03',True),('AC-04',True)]))
    L('    ' + kca_box(xs[2], row2_y, cw, row2_h, SKY,
        'COST &amp; RESOURCE GOVERNANCE',
        ['Token Budget + API Call Limits Per Session',
         'Max Execution Time Per Workflow',
         'Cost Circuit Breakers',
         'Resource Consumption Logging',
         'Autonomy Boundary Per Agent Class'],
        [('AC-06',True),('AU-02',True),('CA-07',True),('PM-09',False)]))

    # ── BOTTOM BAND ───────────────────────────────────────────────────────────
    band_y = 528; band_h = 105
    lw = 460; rw = 458; rx2 = 490

    L('    <!-- BOTTOM BAND -->')
    L('    ' + bottom_panel(10, band_y, lw, band_h, NAVY,
        'AGENT LIFECYCLE &amp; DEPLOYMENT',
        [('Versioned Prompts &amp; Tool Configs (CI/CD)', ['CM-03']),
         ('Adversarial + Statistical Agent Testing',       ['SA-11','CM-04']),
         ('Pre-Deployment Risk Assessment',                ['RA-03']),
         ('Credential Revoke on Decommission',             ['CM-02','IA-05'])],
        [('CM-03',False),('SA-11',False),('RA-03',False),('CM-02',False),('IA-05',False)]))
    L('    ' + bottom_panel(rx2, band_y, rw, band_h, TEAL,
        'AGENT INCIDENT RESPONSE',
        [('Kill Switch (Halt + Access Revoke)',      ['IR-04']),
         ('Blast Radius Assessment',                 ['SA-09','IR-06']),
         ('Agent-Specific IR Runbooks',              ['IR-01']),
         ('Anomaly Detection on Agent Behaviour',    ['SI-04','AU-02'])],
        [('IR-04',True),('IR-06',False),('IR-01',False),('SI-04',False),('AU-02',True)]))

    # -- LEGEND --
    L("    <!-- LEGEND STRIP -->")
    leg_y = 636
    leg_h = 18
    L(f'    <rect x="10" y="{leg_y}" width="940" height="{leg_h}" rx="4" ry="4" fill="{NIGHT}" fill-opacity="0.06" stroke="{NAVY}" stroke-opacity="0.18" stroke-width="1"/>')
    L(f'    <text font-family="{FONT}" font-size="7.5" font-weight="700" fill="{NAVY}" fill-opacity="0.65" letter-spacing="0.8" x="22" y="{leg_y+9}" dominant-baseline="central">KEY:</text>')
    cp = pill_path(54, leg_y+1, 34, 16, 8)
    L(f'    <path d="{cp}" fill="{NIGHT}" fill-opacity="0.12" stroke="{NAVY}" stroke-opacity="0.6" stroke-width="1"/>')
    L(f'    <text font-family="{FONT}" font-size="7.5" fill="{NAVY}" text-anchor="middle" dominant-baseline="central" x="71" y="{leg_y+9}">XX-00</text>')
    L(f'    <text font-family="{FONT}" font-size="7.5" fill="#475569" x="93" y="{leg_y+9}" dominant-baseline="central">Critical control</text>')
    ip = pill_path(196, leg_y+1, 34, 16, 8)
    L(f'    <path d="{ip}" fill="{TEAL}" fill-opacity="0.12" stroke="{TEAL}" stroke-opacity="0.4" stroke-width="1"/>')
    L(f'    <text font-family="{FONT}" font-size="7.5" fill="#005F7F" text-anchor="middle" dominant-baseline="central" x="213" y="{leg_y+9}">XX-00</text>')
    L(f'    <text font-family="{FONT}" font-size="7.5" fill="#475569" x="235" y="{leg_y+9}" dominant-baseline="central">Important control</text>')
    L(f'    <text font-family="{FONT}" font-size="7.5" fill="#64748B" x="390" y="{leg_y+9}" dominant-baseline="central">Supply Chain: SR-02 · SR-03 · SA-08 · SA-09 · CM-03 · CM-04 · RA-05 · SC-04</text>')
    L(f'    <text font-family="{FONT}" font-size="6.5" fill="#94A3B8" text-anchor="middle" x="796.0" y="378">MAESTRO Layer 6 (Agent Integration) · Layer 3 (Agent Runtime) · Layer 2 (Orchestration)</text>')
    L(f'    <text font-family="{FONT}" font-size="6.5" fill="#94A3B8" text-anchor="middle" x="481.0" y="378">OWASP AI-08 (Vector/Embedding Weakness) · AI-09 (Misinformation) · AI-10 (Unbounded Consumption)</text>')
    L(f'    <text font-family="{FONT}" font-size="6.5" fill="#94A3B8" text-anchor="middle" x="163.0" y="378">MITRE ATLAS: AML.T0049 (Exploit Public-Facing LLM) · AML.T0054 (LLM Jailbreak)</text>')
    L(f'    <text font-family="{FONT}" font-size="6.5" fill="#94A3B8" text-anchor="middle" x="796.0" y="157">AI-03 (Supply Chain) · AI-05 (Insecure Output) · AI-07 (System Prompt Leakage)</text>')
    L(f'    <text font-family="{FONT}" font-size="6.5" fill="#94A3B8" text-anchor="middle" x="481.0" y="157">OWASP AI-01 (Prompt Injection) · AI-02 (Sensitive Info Disclosure) · AI-06 (Excessive Agency)</text>')
    L(f'    <text font-family="{FONT}" font-size="6.5" fill="#94A3B8" text-anchor="middle" x="163.0" y="157">MITRE ATLAS: AML.T0051 (LLM Prompt Injection) · AML.T0043 (Craft Adversarial Data)</text>')
    L("    <!-- THREAT ANNOTATIONS -->")
    # -- THREAT CONTEXT ANNOTATIONS --
    # ── FOOTER ────────────────────────────────────────────────────────────────
    fy = 645
    L('    <!-- FOOTER -->')
    L(f'    <rect x="0" y="{fy}" width="960" height="75" fill="{NIGHT}"/>')
    L(f'    <line x1="0" y1="{fy}" x2="960" y2="{fy}" stroke="{TEAL}" '
      f'stroke-opacity="0.4" stroke-width="1"/>')
    L(f'    <text font-family="{FONT}" font-size="8.5" fill="{WHITE}" fill-opacity="0.6" '
      f'x="16" y="{fy+14}" dominant-baseline="central">'
      f'Related: SP-027 Secure LLM Usage \u00b7 SP-045 AI Governance \u00b7 '
      f'SP-030 API Security \u00b7 SP-029 Zero Trust Architecture</text>')
    L(f'    <text font-family="{FONT}" font-size="8.5" fill="{TEAL}" '
      f'text-anchor="end" x="948" y="{fy+14}" dominant-baseline="central">'
      f'OWASP Top 10 Agentic Applications 2025 \u00b7 MAESTRO \u00b7 Anthropic MCP \u00b7 MITRE ATLAS</text>')
    L(f'    <text font-family="{FONT}" font-size="8" fill="{WHITE}" fill-opacity="0.4" '
      f'x="16" y="{fy+30}" dominant-baseline="central">'
      f'SP-047: Secure Agentic AI Frameworks \u00b7 33 NIST 800-53 Rev 5 controls \u00b7 '
      f'Authors: Aurelius, Vitruvius \u00b7 Draft \u00b7 2026-02-24</text>')

    all_ctrls = [
        'AC-03','AC-04','AC-05','AC-06','AU-02','AU-03','CA-07',
        'CM-07','IR-04','SA-09','SC-07','SI-10',
        'CM-02','CM-03','CM-08','IA-04','IA-05','IR-01','IR-06',
        'PM-09','RA-03','SA-04','SA-11','SC-28','SC-39',
        'SI-04','SR-02','SR-03',
    ]
    bx = 16; badge_y_f = fy + 48
    for ctrl in all_ctrls:
        bw = max(34, int(len(ctrl)*6.0 + 14))
        if bx + bw > 948:
            break
        p2 = pill_path(bx, badge_y_f, bw, 16, 8)
        is_crit = ctrl in CRITICAL_SET
        fc = NIGHT if is_crit else TEAL
        tc2 = WHITE if is_crit else '#A8E0F5'
        slug = ctrl.lower()
        L(f'    <a xlink:href="/controls/{slug}">')
        L(f'      <path d="{p2}" fill="{fc}" fill-opacity="0.4" '
          f'stroke="{WHITE}" stroke-opacity="0.2" stroke-width="0.8"/>')
        L(f'      <text font-family="{FONT}" font-size="7.5" fill="{tc2}" '
          f'text-anchor="middle" dominant-baseline="central" '
          f'x="{bx+bw/2:.1f}" y="{badge_y_f+8:.1f}">{ctrl}</text>')
        L(f'    </a>')
        bx += bw + 3

    L('  </g>')
    L('</svg>')
    return '\n'.join(lines)


if __name__ == '__main__':
    svg = build_svg()
    with open(OUTPUT, 'w', encoding='utf-8') as fh:
        fh.write(svg)
    sz = len(svg.encode('utf-8'))
    print(f'Written : {OUTPUT}')
    print(f'Lines   : {svg.count(chr(10))}')
    print(f'Bytes   : {sz:,}  ({"OK" if sz > 50000 else "WARNING: too small"})')
